# This file is used by pre-push  to validate our stylesheets.
# It should be kept in sync with scss-lint.yml, which is used
# by Policial during the Github build process.

files:
  include: 'src/app/**/*.scss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  border-zero: 1
  clean-import-paths: 1
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 1
  function-name-format: 1
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: true
  mixin-name-format: 1
  mixins-before-declarations: 1
  nesting-depth: 0
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  placeholder-in-extend: 0
  placeholder-name-format: 1
  property-sort-order: 1
  variable-name-format: 1
