# scss-lint is deprecated, however used by Policial during the Github
# build process. For that reason, we should keep this in sync with
# .sass-lint.yml, which is used by pre-push.

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    ignored_types: id

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: false

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true

  Indentation:
    enabled: true
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero

  MergeableSelector:
    enabled: true

  NameFormat:
    enabled: true

  NestingDepth:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    extra_properties:
      - mso-table-lspace
      - mso-table-rspace
    enabled: true

  QualifyingElement:
    enabled: true

  SelectorDepth:
    enabled: true

  SelectorFormat:
    enabled: false
    convention: hyphenated_BEM

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VendorPrefix:
    enabled: true
    excluded_identifiers: ['selection']

  ZeroUnit:
    enabled: true
